/**
 * Constantes partagées entre le client et le serveur
 */

export const LIMITS = {
  USERNAME_MIN: 2,
  USERNAME_MAX: 30,
  ROOM_CODE_LENGTH: 6,
  CHAT_MESSAGE_MAX: 500,
  PLAYERS_MIN: 2,
  PLAYERS_MAX: 8,
} as const

export const TIMEOUTS = {
  TURN_DEFAULT: 60000,
  RECONNECT: 120000,
  AFK_WARNING: 45000,
  GAME_IDLE: 600000, // 10 minutes
} as const

export const ERROR_CODES = {
  // Auth
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  USERNAME_TAKEN: "USERNAME_TAKEN",
  EMAIL_TAKEN: "EMAIL_TAKEN",
  NOT_AUTHENTICATED: "NOT_AUTHENTICATED",

  // Room
  ROOM_NOT_FOUND: "ROOM_NOT_FOUND",
  ROOM_FULL: "ROOM_FULL",
  ROOM_CLOSED: "ROOM_CLOSED",
  ALREADY_IN_ROOM: "ALREADY_IN_ROOM",
  NOT_IN_ROOM: "NOT_IN_ROOM",

  // Game
  GAME_NOT_STARTED: "GAME_NOT_STARTED",
  GAME_ALREADY_STARTED: "GAME_ALREADY_STARTED",
  NOT_YOUR_TURN: "NOT_YOUR_TURN",
  INVALID_ACTION: "INVALID_ACTION",
  NOT_HOST: "NOT_HOST",

  // General
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  RATE_LIMITED: "RATE_LIMITED",
} as const

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES]

